// stockItems.js


export const stockItems = [
    { name: 'กุ้ง 20-22 ตัว/กก.', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'กุ้ง 28-30 ตัว/กก.', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'กุ้งเสือ 8 ตัว/กก', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'กุ้งแห้ง', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ไข่ไก่เบอร์ 0', fixedStock: '5 แผง', unit: 'แผง', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ไข่เค็ม', fixedStock: '10 ฟอง', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ไข่เป็ดเบอร์0', fixedStock: '30 ฟอง', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ไข่เยียวม้า', fixedStock: '20 ฟอง', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'คอหมู', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ซี่โครงไก่', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'เนื้อวัวบด', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'เนื้อวัวริบอาย ออสเตรีย', fixedStock: '5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'เนื้อวัวสันนอก', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ปลากระพง 800 กรัม/ตัว', fixedStock: '4 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ปลาทู ขนาดใหญ่', fixedStock: '10 ตัว', unit: 'ตัว', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ปลาสลิด 9-10ตัว/กก', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ปลาหมึกศอก 2-4 ตัว/กก', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ปีกไก่กลาง', fixedStock: '5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'สะโพกไก่เลาะกระดูก', fixedStock: '3 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'สะโพกไก่เลาะกระดูกบด', fixedStock: '4 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ไส้กรอกอีสาน ส.ขอนแก่น', fixedStock: '2 แพ็ค', unit: 'แพ็ค', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'หมูสะโพก', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'หมูสันใน', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'หมูสับปนมัน 25%', fixedStock: '5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'ห่อหมก', fixedStock: '15 ชิ้น', unit: 'ชิ้น', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'แหนมสด ส.ขอนแก่น', fixedStock: '5 แท่ง', unit: 'แท่ง', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'อกไก่ลอกหนัง', fixedStock: '4 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'เอ็นต์แก้วไก่', fixedStock: '5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ไทย' },
    { name: 'กระชายหัว', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'กะหล่ำปลี', fixedStock: '2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'กะหล่ำปลีม่วง', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ข้าวโพดอ่อน', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ข่าอ่อน', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ขิงแก่', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'คะน้าฮ่องกงต้นใหญ่', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'คื่นฉ่าย', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ชะอม', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ต้นหอม', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ตะไคร้', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'แตงร้าน ลูกใหญ่', fixedStock: '2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ถั่วฝักยาว', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบกระเพรา', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบตอง', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบเตย', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบมะกรูด', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบสะระแหน่', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ใบโหระพา', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ผักกาดขาว', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ผักชีไทย', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ผักชีฝรั่ง', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'ผักชีลาว', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'พริกขี้หนูแดงเด็ดก้าน', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'พริกขี้หนูสวนเม็ดเล็ก เขียว', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'พริกชี้ฟ้าแดง', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'พริกชี้ฟ้าเหลือง', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'พริกไทยอ่อน', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'มะเขือเปาะ', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'มะเขือพวงเด็ดขั้ว', fixedStock: '0.1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'มะนาว', fixedStock: '50 ลูก', unit: 'ลูก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'มะม่วงดิบ', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'มะละกอดิบ', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'หอมแขก', fixedStock: '3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'หัวใชเท้า', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'เห็ดฟาง', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'ไทย' },
    { name: 'กระเทียมกลีบเล็ก', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'กระเทียมกลีบใหญ่', fixedStock: '5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'กะทิอร่อยดี', fixedStock: '4 กล่อง', unit: 'กล่อง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'กะปิอย่างดี', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เกร็ดขนมปังฟาร์มเฮ้าส์', fixedStock: '0.5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เกลือปรุงทิพย์', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เกลือเม็ด', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ข้าวหอมมะลิ', fixedStock: '20 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ข้าวเหนียว', fixedStock: '5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ขิงดองกระปุก', fixedStock: '0.5 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'คนอร์ ผง', fixedStock: '2 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'งาขาว', fixedStock: '0.3 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซอสปรุงรสฝาเขียว', fixedStock: '2 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซอสพริกศรีราชา', fixedStock: '2 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซอสมะเขือเทศ', fixedStock: '2 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซอสหอยนางรม 3 แม่ครัว', fixedStock: '1 กล', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซีอิ๊วขาวเด็กสมบูรณ์', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ซีอิ๊วดำเด็กสมบูรณ์', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ตั้งฉ่าย', fixedStock: '1 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เต้าเจี้ยวเด็กสมบูรณ์', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เต้าหู้ไข่', fixedStock: '5 หลอด', unit: 'หลอด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ถั่วลิสงดิบ', fixedStock: '3 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'นมข้นจืด', fixedStock: '6 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำกระเทียมดอง', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำจิ้มไก่ แม่ประนอม', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำตาลทรายแดง', fixedStock: '2 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำตาลปิ๊บ', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำปลา', fixedStock: '4 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำปลาร้าแม่บุญล้ำ ฝาเหลือง', fixedStock: '3 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำพริกเผา ฉั่วฮะเส็ง', fixedStock: '1 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำมันงา', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำมันปาล์ม', fixedStock: '2 ปี๊ป', unit: 'ปี๊ป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำมันพริกเผา', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'น้ำส้มสายชู', fixedStock: '2 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'แป้งโกกิ', fixedStock: '2 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'แป้งทอดกรอบ', fixedStock: '2 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ผงลาบ รสดี', fixedStock: '1 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกแกงเขียวหวาน', fixedStock: '0.5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกแกงคั่วใต้', fixedStock: '0.5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกแกงเผ็ดหยาบ', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกไทยขาว', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกไทยดำ', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'พริกแห้งเล็ก', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'มะขามเปียก', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เม็ดมะม่วงหิมพานต์', fixedStock: '3 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'วุ้นเส้น', fixedStock: '1 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'สาหร่าย', fixedStock: '3 แผ่น', unit: 'แผ่น', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เส้นไวไว', fixedStock: '10 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เส้นหมีกรอบ', fixedStock: '1 แพ็ค', unit: 'แพ็ค', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'หอมเจียว', fixedStock: '0.2 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'เหล้าจีน', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ข้าวสารพนักงาน', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ไทย' },
    { name: 'ไข่กุ้งส้ม', fixedStock: '1 แพ็ค', unit: 'แพ็ค', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ซาลามี่ ( เปปเปอร์โรนี )', fixedStock: '1 แท่ง', unit: 'แท่ง', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ซี่โครงหมู', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ดีปลาหมึก', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ตับเป็ด', fixedStock: '1 ก้อน', unit: 'ก้อน', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'เนื้อบดไทย', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'เนื้อริบอาย ออสเตรีย ตัด 300 กรัม/ชิ้น', fixedStock: '5 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'เนื้อริบอาย ออสเตรีย ตัด 600 กรัม/ชิ้น', fixedStock: '5 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'เนื้อสันในออสเตรเลีย', fixedStock: '5 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'เบคอน', fixedStock: '5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาเก๋า', fixedStock: '5 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาแซลมอน เทร้า แช่แข็ง', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาแซลมอน เทร้า สด', fixedStock: '30 ชิ้น', unit: 'ชิ้น', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาแซลมอนรมควัน (ราคา/กก.) / ชิ้น', fixedStock: '0.5 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาหิมะ ( ตัว )', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาหิมะ 200 กรัม/ชิ้น', fixedStock: '7 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปาร์มาแฮม (เกรด A)', fixedStock: '0.5 ขา', unit: 'ขา', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'พ็อคช้อป 300 กรัม/ชิ้น', fixedStock: '10 ที่', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'แลมป์แลค (ออสเตรเลีย) ซี่โครงแกละ', fixedStock: '1 โครง', unit: 'โครง', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไส้กรอกไก่คอกเทล', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไส้กรอกชีส 6"', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไส้กรอกสโมค ฟาร์เมอร์', fixedStock: '3 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไส้กรอกหมูพริกไทยดำ', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไส้กรอกหมูสด 6"', fixedStock: '1 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'หมูสามชั้น', fixedStock: '3 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'หอยเชลล์', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'หอยแมลงภู่นิวซีแลนด์ (Size L)', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'แอนโชวี่', fixedStock: '0.5', unit: '', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'แฮม', fixedStock: '2 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'อิตาเลี่ยน' },
    { name: 'คอส', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'แคนตาลูป ญี่ปุ่น', fixedStock: '1 ลูก', unit: 'ลูก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'แครอท', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไควาเรท', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ดอกกะหล่ำ', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ต้นหอมญี่ปุ่น', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'แตงกวาญี่ปุ่น', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'แตงซูกินิ', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ถั่วลันเตาญี่ปุ่น', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไทม์', fixedStock: '0.01 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'บล็อคโคลี่', fixedStock: '0.3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เบบี้ครอท', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ผักกาดแก้ว', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ผักโขม', fixedStock: '3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'พริกยักษ์เขียว', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'พริกยักษ์แดง', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'พริกยักษ์เหลือง', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'พลาสลี่', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เฟร้นฟรายเส้นตรงใหญ่', fixedStock: '5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะเขือเทศเชอรี่', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะเขือเทศเชอรี่ติดก้าน', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะเขือเทศใหญ่', fixedStock: '3 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'มันฝรั่ง', fixedStock: '5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'มิกซ์สลัด', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ร็อกเก็ต', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ราสเบอร์รี่แช่แข็ง', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เรดิซ', fixedStock: '0.2 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'โรสแมรี่', fixedStock: '0.01 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เลม่อนนอก', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'หอมหัวใหญ่', fixedStock: '5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดเข็มทอง', fixedStock: '0.1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดชิเมจิ', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดแชมปิยอง', fixedStock: '0.5 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดหอมสด', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดหอมแห้ง', fixedStock: '1 กก', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'เห็ดออรินจิ', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'อิตาเลี่ยน' },
    { name: 'ขนมปังแถว', fixedStock: '0.5 แถว', unit: 'แถว', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ขนมปังฝรั่งเศส', fixedStock: '3 แถว', unit: 'แถว', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ข้าวโพดเมล็ด', fixedStock: '24 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'คะนอซุปไก่ก้อน', fixedStock: '2 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'แคปเปอร์เม็ดใหญ่', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ซอสโชวยุ', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ซอสโตเมโตเพลส', fixedStock: '2 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ซอสเทริยากิ', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เต้าหู้ก้อนญี่ปุ่นชนิดเนื้อนิ่ม', fixedStock: '4 แพ็ค', unit: 'แพ็ค', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำผึ้ง เวชพงษ์', fixedStock: '0.5 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำมันมะกอก Extra', fixedStock: '1 กล', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำมันมะกอก Pomas', fixedStock: '2 กล', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำมันสลัด', fixedStock: '0.5 กล', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำมันเห็ดทรัฟเฟิล', fixedStock: '0.25 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำส้มแดง (Vinegar)', fixedStock: '0.5 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'น้ำสลัดงา ซีอิ๊วซี่ปุ่น', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เนยจืด อราวลี่', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'บราว์ซอส', fixedStock: '2 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'บาลซามิก', fixedStock: '0.25 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'บูลชีส', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เบคกิ้งโซดา', fixedStock: '1 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ใบลีฟ', fixedStock: '1 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'แป้งพิซซ่า', fixedStock: '1 กส', unit: 'กส', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ปลาโอแห้ง ญี่ปุ่น', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'แป้งลาซอนย่า', fixedStock: '0.5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ผงปาปริก้า', fixedStock: '0.25 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'พามาซานชีส', fixedStock: '2 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มอลซาเรราชีส', fixedStock: '5 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มอสน้ำ', fixedStock: '1 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะกอกเขียวไร้เมล็ด', fixedStock: '6 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะกอกดำไร้เมล็ด', fixedStock: '12 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มะเขือเทศปอกเปลือก', fixedStock: '12 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มัสตาส ( เม็ด )', fixedStock: '1 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'มัสตาส อโมรา', fixedStock: '3 ขวด', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ยีสต์ผง', fixedStock: '1 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เรียวมายองเนส', fixedStock: '6 ถุง', unit: 'ถุง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ลูกพีซกระป๋อง', fixedStock: '0.5 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'วิปปิ้งครีม', fixedStock: '6 กล่อง', unit: 'กล่อง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไวน์ขาว (ทำอาหาร)', fixedStock: '3 ลิตร', unit: 'ลิตร', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'ไวน์แดง (ทำอาหาร)', fixedStock: '3 ลิตร', unit: 'ลิตร', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'สัปปะรดแว่น', fixedStock: '24 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เส้นเพนนี่', fixedStock: '6 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เส้นเฟสตูชินี่', fixedStock: '10 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เส้นสปาเก็ตตี้ #4', fixedStock: '20 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เส้นสปาเก็ตตี้เส้นดำ', fixedStock: '2 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'เส้นแองเจิ้ลแฮร์', fixedStock: '20 ห่อ', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'อัลมอนสไลด์', fixedStock: '0.3 กก', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'อารีกาโน', fixedStock: '1 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' },
    { name: 'อาโรมาต', fixedStock: '3 กป', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'อิตาเลี่ยน' }
];
